import {SettingsRow as Row} from './SettingsRow';
import {Popover,PopoverTrigger,PopoverContent} from '@/components/ui/popover';
import {useEffect,useState,useCallback} from 'react';
import {Link,useSearchParams} from 'react-router';
import {agentStatus,agentRequest,type AgentStatus,type AiConfig} from '@/lib/agentClient';
import {useProject} from '@/project/context';
import {saveProjectConfiguration} from './projectSettings';
import {projectConfigPath,legacyProjectConfigPath} from '@/lib/managementDir';
import {projectConfiguration} from './model';
import {ProviderConfigurationDialog} from './ProviderConfiguration';
const field='min-h-9 rounded-lg border border-input bg-background px-3 py-2 text-xs text-foreground disabled:opacity-40';
const thinkingNames:Record<string,string>={off:'关闭',minimal:'最少',low:'低',medium:'中',high:'高',xhigh:'最高'};
export function AiSettingsView({scope}:{scope:'global'|'project'}){
 const [search]=useSearchParams(),{project,setProject,busy}=useProject(),[status,setStatus]=useState<AgentStatus|null>(null),[provider,setProvider]=useState(''),[configuring,setConfiguring]=useState<string|null>(null),[message,setMessage]=useState(''),[working,setWorking]=useState(false),[providerQuery,setProviderQuery]=useState(''),[providerOpen,setProviderOpen]=useState(false);
 const [custom,setCustom]=useState({provider:'',baseUrl:'',model:'',name:'',api:'openai-completions',contextWindow:'',maxTokens:''});
 const global=scope==='global';
 const refresh=useCallback(async()=>{const result=await agentStatus();setStatus(result);setProvider(current=>current||result.providers.find(item=>item.id===search.get('provider'))?.id||result.providers.find(item=>item.auth.configured)?.id||result.providers[0]?.id||'');},[search]);
 useEffect(()=>{void refresh().catch(error=>setMessage(error.message));},[refresh]);
 const action=async(run:()=>Promise<unknown>,success:string)=>{setWorking(true);setMessage('');try{await run();await refresh();setMessage(success);window.dispatchEvent(new Event('envoi:ai-configured'));}catch(error){setMessage((error as Error).message);}finally{setWorking(false);}};
 const record=project.files.find(file=>file.path===projectConfigPath)??project.files.find(file=>file.path===legacyProjectConfigPath);let overrides:Partial<AiConfig>={};try{overrides=JSON.parse(record?.text??'{}').ai??{};}catch{/* Saving reports invalid project configuration. */}
 const config={...(status?.settings??{model:null,context:'current',tools:'read'}),...(!global?overrides:{})} as AiConfig;
 async function save(patch:Partial<AiConfig>,inherit?:keyof AiConfig){if(!status)return;if(patch.model!==undefined){patch={...patch,provider:patch.model?.split('/')[0]??null,thinking:null};}if(global){await action(()=>agentRequest('settings',{settings:{...status.settings,...patch}}),'已保存');return;}
 if(!project.directory){setMessage('请先连接当前项目。');return;}const next={...overrides,...patch};if(inherit)delete next[inherit];if(inherit==='model'){delete next.provider;delete next.thinking;}
 await action(async()=>{const saved=await saveProjectConfiguration(project,projectConfiguration(project.settings,project.engine),project.rootId,next);setProject(current=>current.id===project.id?{...current,files:current.files.filter(file=>![projectConfigPath,legacyProjectConfigPath,'.gitignore'].includes(file.path)).concat(saved.files.filter(file=>[projectConfigPath,'.gitignore'].includes(file.path)))}:current);},'项目设置已保存');}
 const selected=status?.providers.find(item=>item.id===provider),models=status?.models.filter(model=>model.available)??[],active=models.find(model=>`${model.provider}/${model.id}`===config.model);
 const disabled=working||busy||!status||(!global&&!project.directory);
 const inherited=(key:keyof AiConfig)=>!global&&overrides[key]===undefined;
 if(!global&&!project.directory)return <div className="rounded-xl border border-border bg-card p-6 text-sm text-muted-foreground">当前未连接本地项目。<button className="mt-4 block text-xs text-primary" onClick={()=>window.dispatchEvent(new Event('envoi:open-project'))}>打开项目…</button></div>;
 return <div className="space-y-5">
 {message&&<p role="status" className="text-xs text-muted-foreground">{message}</p>}
 {!status&&<p className="text-xs text-muted-foreground">正在读取本机 AI 配置…</p>}
 {global?<section className="rounded-xl border border-border bg-card px-5">
 <Row label="服务商账号" hint="连接模型服务商，凭据仅保存在本机。"><Popover open={providerOpen} onOpenChange={setProviderOpen}><PopoverTrigger asChild><button aria-label="管理服务商" className={field+' max-w-56 truncate text-left'}>{selected?.name||provider||'选择服务商'}{selected?.auth.configured?' · 已配置':''}</button></PopoverTrigger><PopoverContent align="end" className="w-72 p-2"><input aria-label="搜索服务商" placeholder="搜索服务商" value={providerQuery} onChange={event=>setProviderQuery(event.target.value)} className={field+' mb-2 w-full'}/><div className="max-h-64 overflow-auto">{[...(status?.providers??[])].filter(item=>`${item.name} ${item.id}`.toLowerCase().includes(providerQuery.toLowerCase())).sort((a,b)=>Number(b.auth.configured)-Number(a.auth.configured)||(a.name||a.id).localeCompare(b.name||b.id)).map(item=><button key={item.id} className="block w-full rounded-lg px-3 py-2 text-left text-xs hover:bg-secondary" onClick={()=>{setProvider(item.id);setProviderOpen(false);setProviderQuery('');}}>{item.name||item.id}{item.auth.configured?<span className="ml-2 text-muted-foreground">已配置</span>:null}</button>)}</div></PopoverContent></Popover><button disabled={!selected||working} className={field+' hover:bg-secondary'} onClick={()=>setConfiguring(provider)}>{selected?.auth.configured?'管理连接':'连接'}</button></Row>

 </section>:<section className="rounded-xl border border-border bg-card px-5"><Row label="服务商账号" hint="项目使用本机已配置的账号，凭据不随项目共享。"><Link className="text-xs text-primary" to="/settings/global/ai">管理全局连接</Link></Row></section>}
 <section><h3 className="mb-3 text-sm font-medium">{global?'默认模型与行为':'当前项目 · 继承或覆盖'}</h3><div className="rounded-xl border border-border bg-card px-5">
 <Row label="模型" hint={global?'项目默认继承此选择。':inherited('model')?'继承全局模型': '当前项目覆盖'}><select aria-label="AI 默认模型" disabled={disabled} className={field+' max-w-full sm:max-w-xs'} value={inherited('model')?'inherit':config.model??''} onChange={event=>void(event.target.value==='inherit'?save({},'model'):save({model:event.target.value||null}))}>{!global&&<option value="inherit">继承全局</option>}<option value="">未选择</option>{config.model&&!active&&<option disabled value={config.model}>{config.model} · 当前目录不可用</option>}{models.map(model=><option key={model.provider+'/'+model.id} value={model.provider+'/'+model.id}>{model.provider} / {model.name}</option>)}</select></Row>
 <Row label="思考程度" hint={!config.model?'选择模型后显示可用思考档位':!active?'当前选择在模型目录中不可用。':active.thinkingLevels.length?'仅列出当前模型支持的档位。':'当前模型未提供可调思考档位。'}><select aria-label="AI 默认思考程度" disabled={disabled||!active?.thinkingLevels.length} className={field} value={inherited('thinking')?'inherit':config.thinking??''} onChange={event=>void(event.target.value==='inherit'?save({},'thinking'):save({thinking:event.target.value||null}))}>{!global&&<option value="inherit">继承全局</option>}<option value="">模型默认</option>{config.thinking&&!active?.thinkingLevels.includes(config.thinking)&&<option disabled value={config.thinking}>{config.thinking} · 不可用</option>}{active?.thinkingLevels.map(level=><option key={level} value={level}>{thinkingNames[level]||level}</option>)}</select></Row>
 {(['context','tools'] as const).map(key=><Row key={key} label={key==='context'?'文档上下文':'文件工具权限'} hint={key==='context'?'选择是否向模型提供当前文档的编辑缓冲。':'工具仅访问当前已配置项目内的非隐藏文件。'}><select aria-label={key==='context'?'AI 文档上下文':'AI 文件工具权限'} disabled={disabled} className={field} value={inherited(key)?'inherit':config[key]} onChange={event=>void(event.target.value==='inherit'?save({},key):save({[key]:event.target.value}))}>{!global&&<option value="inherit">继承全局</option>}<option value="none">不启用</option>{key==='context'?<option value="current">当前文档</option>:<><option value="read">只读项目文件</option><option value="write">允许修改（需先保存草稿）</option></>}</select></Row>)}
 </div></section>
 {global&&<details id="manual-model" className="rounded-xl border border-border bg-background/40 p-4"><summary className="cursor-pointer text-sm font-medium">高级 · 手动配置兼容模型</summary><p className="mt-2 text-xs leading-relaxed text-muted-foreground">用于尚无目录适配的接口。按服务商文档填写真实模型与参数，保存后再连接账号。</p><div className="mt-4 grid gap-3 sm:grid-cols-2">{(['provider','baseUrl','model','name','contextWindow','maxTokens'] as const).map(key=><label className="text-xs" key={key}>{{provider:'服务商标识',baseUrl:'服务地址',model:'真实模型 ID',name:'显示名称',contextWindow:'上下文窗口',maxTokens:'最大输出'}[key]}<input value={custom[key]} onChange={event=>setCustom(current=>({...current,[key]:event.target.value}))} className={field+' mt-1 w-full'}/></label>)}<label className="text-xs">接口类型<select aria-label="自定义模型接口类型" value={custom.api} onChange={event=>setCustom(current=>({...current,api:event.target.value}))} className={field+' mt-1 w-full'}><option value="openai-completions">OpenAI Chat Completions</option><option value="anthropic-messages">Anthropic Messages</option><option value="google-generative-ai">Google Generative AI</option></select></label><div className="flex items-end"><button disabled={working||!custom.provider||!custom.baseUrl||!custom.model||!custom.contextWindow||!custom.maxTokens} className={field+' hover:bg-secondary'} onClick={()=>void action(()=>agentRequest('custom-provider',custom),'已添加，请连接该服务商账号')}>添加模型</button></div></div>{status&&<p className="mt-4 break-all text-xs text-muted-foreground">本机数据：{status.storage.dataDir}</p>}</details>}
 <ProviderConfigurationDialog provider={status?.providers.find(item=>item.id===configuring)??null} onClose={()=>setConfiguring(null)} onSaved={()=>{void refresh().catch(error=>setMessage(error.message));window.dispatchEvent(new Event('envoi:ai-configured'));}}/>
 </div>;
}
