import {ModelCatalogInfo} from '@/components/ModelCatalogInfo';
import {ProviderConfiguration} from './ProviderConfiguration';
import {useEffect,useState,useCallback} from 'react';import {Link,useSearchParams} from 'react-router';import {agentStatus,agentRequest,type AgentStatus,type AiConfig} from '@/lib/agentClient';import {useProject} from '@/project/context';import {saveProjectConfiguration} from './projectSettings';import {projectConfiguration} from './model';
const field='w-full rounded border border-input bg-background px-3 py-2 text-sm';
export function AiSettingsView({scope}:{scope:'global'|'project'}){const [search]=useSearchParams();const {project,setProject,busy}=useProject(),[status,setStatus]=useState<AgentStatus|null>(null),[provider,setProvider]=useState(''),[message,setMessage]=useState(''),[working,setWorking]=useState(false),[query,setQuery]=useState(''),[custom,setCustom]=useState({provider:'',baseUrl:'',model:'',name:'',api:'openai-completions',contextWindow:'32000',maxTokens:'4096'});
 const refresh=useCallback(async()=>{try{const result=await agentStatus();setStatus(result);setProvider(current=>result.providers.some(provider=>provider.id===search.get('provider'))?search.get('provider')!:current||result.providers[0]?.id||'');setMessage(result.available?'配置检测完成（未发送推理请求）。':'Pi 已安装；尚未找到配置了凭据的模型。');}catch(error){setMessage((error as Error).message);}},[search]);
 useEffect(()=>{void refresh();},[refresh]);
 const action=async(run:()=>Promise<unknown>,success:string)=>{setWorking(true);try{await run();setMessage(success);await refresh();window.dispatchEvent(new Event('paperdesk:ai-configured'));}catch(error){setMessage((error as Error).message);}finally{setWorking(false);}};
 const record=project.files.find(file=>file.path==='.paperdesk/project.json');let overrides:Partial<AiConfig>={};try{overrides=JSON.parse(record?.text??'{}').ai??{};}catch{/* Invalid project JSON is handled when saving. */}
 const config={...(status?.settings??{model:null,context:'current',tools:'read'}),...overrides} as AiConfig;
 const save=async(patch:Partial<AiConfig>,inherit?:keyof AiConfig)=>{if(!status)return;if(patch.model!==undefined&&patch.model!=='inherit'){patch={...patch,provider:patch.model?.split('/')[0]??null,thinking:null};}if(scope==='global'){await action(()=>agentRequest('settings',{settings:{...status.settings,...patch}}),'全局 AI 设置已保存。');return;}if(!project.directory){setMessage('请先打开并连接真实项目。');return;}const next={...overrides,...patch};if(inherit)delete next[inherit];if(inherit==='model'){delete next.provider;delete next.thinking;}await action(async()=>{const saved=await saveProjectConfiguration(project,projectConfiguration(project.settings,project.engine),project.rootId,next);setProject(current=>current.id===project.id?{...current,files:current.files.filter(file=>!['.paperdesk/project.json','.gitignore'].includes(file.path)).concat(saved.files.filter(file=>['.paperdesk/project.json','.gitignore'].includes(file.path)))}:current);},'项目 AI 覆盖已保存。');};
 const selected=status?.providers.find(item=>item.id===provider),available=status?.models.filter(model=>model.provider===provider&&`${model.name} ${model.id}`.toLowerCase().includes(query.toLowerCase()))??[];
 return <div className="h-full overflow-auto p-7"><div className="mx-auto max-w-4xl"><div className="flex items-center gap-4"><h1 className="text-xl font-semibold">AI 设置</h1><Link className="text-xs text-primary" to={`/settings/${scope}/general`}>返回设置</Link><Link className="ml-auto text-xs text-primary" to={`/settings/${scope==='global'?'project':'global'}/ai`}>{scope==='global'?'当前项目覆盖':'全局服务商'}</Link></div><p className="my-3 text-xs text-muted-foreground">Pi 是本机运行时，模型可能由云服务商提供。配置检测不会进行推理；聊天发送才调用模型。</p><p role="status" className="mb-4 text-sm text-amber-200">{message}</p><button className="mb-4 text-xs text-primary" onClick={()=>void refresh()}>重新检测配置</button>
 {scope==='global'&&status&&<div className="grid gap-5 md:grid-cols-[180px_1fr]"><nav className="max-h-96 overflow-auto rounded-lg border border-border bg-card p-2">{status.providers.map(item=><button key={item.id} onClick={()=>{setProvider(item.id);}} className={`block w-full rounded px-3 py-2 text-left text-xs ${provider===item.id?'bg-accent text-primary':''}`}><span>{item.name||item.id}</span><span className="mt-1 block text-[10px] text-muted-foreground">{item.auth.configured?'已配置':'待配置'}</span></button>)}</nav><section className="rounded-xl border border-border bg-card p-5"><h2 className="text-lg">{selected?.name||provider}</h2><p className="my-2 text-xs text-muted-foreground">{selected?.auth.configured?`凭据来源：${selected.auth.source??'Pi'}`:'尚未配置凭据'}</p>{selected&&<ProviderConfiguration key={selected.id} provider={selected} onSaved={()=>{void refresh();window.dispatchEvent(new Event('paperdesk:ai-configured'));}} />}<ModelCatalogInfo provider={provider} catalog={selected?.catalog} onRefresh={refresh}/><input aria-label="筛选服务商模型" value={query} onChange={e=>setQuery(e.target.value)} placeholder="筛选模型…" className={field+' mt-5'} /><div className="mt-2 max-h-52 overflow-auto">{available.map(model=><button key={model.id} disabled={!model.available||working} onClick={()=>void save({model:`${model.provider}/${model.id}`})} className="block w-full rounded px-2 py-2 text-left text-xs hover:bg-secondary disabled:opacity-40">{model.name} <span className="text-muted-foreground">{model.id}{model.available?'':' · '+(model.unavailableReason??'不可用')}</span></button>)}</div></section></div>}
 <section className="mt-5 space-y-4 rounded-xl border border-border bg-card p-5"><h2 className="text-sm font-medium">{scope==='global'?'默认行为':'当前项目 · 继承或覆盖'}</h2><label className="block text-xs">模型<select aria-label="AI 默认模型" disabled={working||busy} className={field+' mt-1'} value={scope==='project'&&overrides.model===undefined?'inherit':scope==='global'?status?.settings.model??'':config.model??''} onChange={e=>void save({model:e.target.value||null},e.target.value==='inherit'?'model':undefined)}>{scope==='project'&&<option value="inherit">继承全局</option>}<option value="">未选择</option>{(scope==='global'?status?.settings.model:config.model)&&!status?.models.some(model=>model.available&&`${model.provider}/${model.id}`===(scope==='global'?status?.settings.model:config.model))&&<option disabled value={(scope==='global'?status?.settings.model:config.model)??''}>{scope==='global'?status?.settings.model:config.model} · 当前目录不可用</option>}{status?.models.filter(model=>model.available).map(model=><option key={model.provider+'/'+model.id} value={model.provider+'/'+model.id}>{model.provider} / {model.name}</option>)}</select></label>{(['context','tools'] as const).map(key=><label key={key} className="block text-xs">{key==='context'?'文档上下文':'文件工具权限'}<select disabled={working||busy} className={field+' mt-1'} value={scope==='project'&&overrides[key]===undefined?'inherit':scope==='global'?status?.settings[key]??'none':config[key]} onChange={e=>void save({[key]:e.target.value},e.target.value==='inherit'?key:undefined)}>{scope==='project'&&<option value="inherit">继承全局</option>}<option value="none">不启用</option>{key==='context'?<option value="current">当前文档编辑缓冲（标注草稿）</option>:<><option value="read">只读项目文件</option><option value="write">允许修改项目文件（需先保存草稿）</option></>}</select></label>)}<p className="text-xs text-muted-foreground">文件工具限定已绑定项目内非隐藏文件；不提供 shell 或项目外访问。项目设置随项目共享，凭据与会话不共享。</p></section>
 {scope==='global'&&<details id="manual-model" className="mt-5 rounded-xl border border-border bg-card p-5"><summary className="cursor-pointer text-sm">高级 · 添加兼容服务商</summary><div className="mt-4 grid gap-3">{(['provider','baseUrl','model','name','contextWindow','maxTokens'] as const).map(key=><label className="text-xs" key={key}>{{provider:'服务商标识（字母/数字/横线）',baseUrl:'服务地址',model:'真实模型 ID',name:'显示名称',contextWindow:'上下文窗口（按服务商文档填写）',maxTokens:'最大输出（按服务商文档填写）'}[key]}<input value={custom[key]} onChange={e=>setCustom(current=>({...current,[key]:e.target.value}))} className={field+' mt-1'} /></label>)}<select value={custom.api} onChange={e=>setCustom(current=>({...current,api:e.target.value}))} className={field}><option value="openai-completions">OpenAI 兼容 Chat Completions</option><option value="anthropic-messages">Anthropic Messages</option><option value="google-generative-ai">Google Generative AI</option></select><button disabled={working} className="text-sm text-primary" onClick={()=>void action(()=>agentRequest('custom-provider',custom),'兼容服务商已添加，请继续配置凭据。')}>添加服务商与模型</button></div></details>}
 {status&&<p className="mt-5 text-xs text-muted-foreground">本机数据目录：{status.storage.dataDir} · Pi 凭据：{status.storage.credentials}</p>}
 </div></div>;
}
