import {AiSettingsView} from "@/settings/AiSettingsView";
import {ShortcutsView} from "@/settings/ShortcutsView";
import {useEffect,useState} from 'react';
import {NavLink,useLocation,Link} from 'react-router';
import {useProject} from '@/project/context';
import {usePreferences} from '@/settings/context';
import {useSettings} from '@/settings/useSettings';
import {accents,editorFonts,textFonts,projectConfiguration,settingCategories,type SettingsCategory,type SettingsScope,type Engine} from '@/settings/model';
const input='min-h-9 py-2 rounded-lg border border-input bg-background px-3 text-xs text-foreground';
function Row({label,hint,children}:{label:string;hint?:string;children:React.ReactNode}){return <div className="flex flex-wrap items-center justify-between gap-4 border-b border-border/50 py-4 last:border-0"><div className="min-w-0"><h3 className="text-[13px] font-medium">{label}</h3>{hint&&<p className="mt-1 max-w-md text-xs leading-relaxed text-muted-foreground">{hint}</p>}</div><div className="flex shrink-0 items-center gap-2">{children}</div></div>;}
function TextAppearance({kind}:{kind:'ui'|'preview'}){const {preferences,update}=usePreferences();const ui=kind==='ui',family=ui?'uiFontFamily':'previewFontFamily',size=ui?'uiFontSize':'previewFontSize',label=ui?'界面':'文本预览';return <><Row label={`${label}字体`} hint="选择字体族；未安装的字体会使用列出的系统回退，不枚举本机字体。"><select aria-label={`${label}字体`} className={input} value={preferences[family]} onChange={e=>update({[family]:e.target.value})}>{Object.entries(textFonts).map(([id,font])=><option key={id} value={id}>{font.name}</option>)}</select></Row><Row label={`${label}字号`} hint={ui?'以 13 px 为默认基准，导航、设置与控件文字按比例调整。':'只影响阅读器 Markdown 与文献卡片。PDF、源码和论文排版不受影响。'}><select aria-label={`${label}字号`} className={input} value={preferences[size]} onChange={e=>update({[size]:Number(e.target.value)})}>{(ui?[12,13,14,15,16]:[12,14,16,18,20]).map(n=><option key={n} value={n}>{n} px</option>)}</select></Row></>;}
function Rules({value,onSave,disabled}:{value:number[];onSave:(rules:number[])=>void;disabled?:boolean}){const [text,setText]=useState(value.join(', ')),[error,setError]=useState('');return <div className="space-y-1"><div className="flex gap-2"><input aria-label="禁用的 ChkTeX 规则" value={text} disabled={disabled} onChange={e=>setText(e.target.value)} placeholder="例如 8, 26；空白表示不禁用" className={input+' w-60'} /><button disabled={disabled} className={input} onClick={()=>{const values=text.trim()?text.split(',').map(v=>Number(v.trim())):[];if(values.some(v=>!Number.isInteger(v)||v<1||v>42)){setError('请输入 1–42 的整数规则编号，以逗号分隔。');return;}setError('');onSave([...new Set(values)].sort((a,b)=>a-b));}}>应用</button></div>{error&&<p role="alert" className="text-xs text-amber-300">{error}</p>}</div>;}
interface Tools {token:string;chktex:{available:boolean;path:string;configured:boolean;error:string};texlab:{available:boolean;path:string;integrationAvailable:boolean};latex:{available:boolean;error?:string;root?:string}}
function LocalTools(){const [tools,setTools]=useState<Tools|null>(null),[path,setPath]=useState(''),[message,setMessage]=useState('正在探测本机工具…'),[busy,setBusy]=useState(false);
 useEffect(()=>{let active=true;void fetch('/api/paperdesk/tools').then(async response=>{if(!response.headers.get('content-type')?.includes('application/json'))throw Error('本地工具服务未连接');return response.json();}).then(result=>{if(active){setTools(result);setPath(result.chktex.path);setMessage('工具配置仅保存在当前本机用户目录，不写入论文项目。');}}).catch(error=>{if(active)setMessage(error.message);});return()=>{active=false;};},[]);
 async function save(value:string|null){if(!tools)return;setBusy(true);try{const response=await fetch('/api/paperdesk/tools',{method:'POST',headers:{'Content-Type':'application/json','X-PaperDesk-Token':tools.token},body:JSON.stringify({chktexPath:value})});const result=await response.json();if(!response.ok)throw Error(result.error);setTools(result);setPath(result.chktex.path);setMessage('本机工具配置已校验并保存；下次编辑检查使用此程序。');}catch(error){setMessage((error as Error).message);}finally{setBusy(false);}}
 return <div className="mt-6 rounded-xl border border-border bg-background/40 p-4"><h3 className="text-sm font-medium">本机工具 · 高级</h3><p role="status" className="mt-2 text-xs text-muted-foreground">{message}</p>{tools&&<><Row label="LaTeX" hint={tools.latex.available?'已探测到本机 TeX 工具链。默认使用服务进程 PATH，可通过 PAPERDESK_TEX_BIN 指定工具目录。':tools.latex.error}><span className="text-xs">{tools.latex.available?'可用':'不可用'}</span></Row><Row label="ChkTeX 程序" hint="默认自动探测。自定义路径必须指向通过版本校验的 chktex 可执行文件，不接受命令参数。"><span className="text-xs">{tools.chktex.available?'可用':'不可用'}</span></Row><div className="flex flex-wrap gap-2"><input aria-label="ChkTeX 可执行路径" value={path} onChange={e=>setPath(e.target.value)} className={input+' min-w-0 flex-1 font-editor'} /><button disabled={busy} className={input} onClick={()=>void save(path)}>校验并保存</button><button disabled={busy} className={input} onClick={()=>void save(null)}>恢复自动探测</button></div><p className="mt-4 text-xs text-muted-foreground">TexLab：{tools.texlab.available?'发现本地程序':'未检测到'}。当前未集成 LSP 会话，不提供无效的补全或诊断开关。</p></>}</div>;
}
export function SettingsView(){
 const {project,busy}=useProject(),{preferences,update,error}=usePreferences(),{configuration,effective,save}=useSettings();
 const parts=useLocation().pathname.split('/');const scope=(parts[2]??'global') as SettingsScope,category=(parts[3]??'general') as SettingsCategory;
 const global=scope==='global';
 const [access,setAccess]=useState<{id:string;ok:boolean;reason:string}|null>(null);
 useEffect(()=>{let active=true;if(scope==='project')void(async()=>{if(!project.directory){if(active)setAccess({id:project.id,ok:false,reason:'当前未连接本地项目。请打开论文目录后设置项目覆盖。'});return;}try{if(await project.directory.queryPermission({mode:'readwrite'})!=='granted')throw Error('项目目录权限当前不可用，请从项目菜单恢复。');for await(const entry of project.directory.entries()){void entry;break;}if(active)setAccess({id:project.id,ok:true,reason:''});}catch(error){if(active)setAccess({id:project.id,ok:false,reason:(error as Error).name==='NotFoundError'?'项目目录已移动或不存在，请打开迁移后的新位置；这不是再次授权 Git。':(error as Error).message});}})();return()=>{active=false;};},[scope,project.id,project.directory]);
 const available=access?.id===project.id&&access.ok;
 const override=(key:'engine'|'lintEnabled'|'disabledRules',value:unknown)=>void save(projectConfiguration({version:1,overrides:{...configuration.overrides,[key]:value}}).overrides);
 const inheritance=(key:keyof typeof configuration.overrides)=>configuration.overrides[key]===undefined?'继承全局':'当前项目覆盖';
 if(category==='ai')return <AiSettingsView scope={scope} />;
 if((category as string)==='shortcuts')return <ShortcutsView />;
 return <div className="flex h-full flex-col bg-background"><header className="border-b border-border px-7 py-5"><div className="flex items-center justify-between gap-4"><div><h1 className="text-xl font-semibold">设置</h1><p className="mt-1 text-xs text-muted-foreground">全局偏好保留在当前浏览器；项目覆盖仅写入所选论文配置。</p></div><div className="flex rounded-lg border border-border bg-card p-1">{(['global','project'] as const).map(value=><NavLink key={value} to={`/settings/${value}/${category}`} className={`rounded-md px-4 py-2 text-xs ${scope===value?'bg-accent text-primary':'text-muted-foreground'}`}>{value==='global'?'全局设置':'当前项目'}</NavLink>)}</div></div></header>
 <div className="flex min-h-0 flex-1"><nav aria-label="设置分类" className="w-44 shrink-0 space-y-1 border-r border-border bg-card/50 p-3">{Object.entries(settingCategories).map(([id,label])=><NavLink end key={id} to={`/settings/${scope}/${id}`} className={({isActive})=>`block rounded-lg px-3 py-2.5 text-xs ${isActive?'bg-accent text-primary':'text-muted-foreground hover:bg-secondary'}`}>{label}</NavLink>)}</nav>
 <div className="min-w-0 flex-1 overflow-auto p-7"><div className="mx-auto max-w-3xl"><h2 className="mb-3 text-base font-medium">{settingCategories[category]}</h2>{error&&<p role="alert" className="mb-4 text-xs text-amber-300">{error}</p>}
 {!global&&!available?<div className="rounded-xl border border-border bg-card p-6 text-sm text-muted-foreground">{access?.id===project.id?access.reason:'正在检查项目连接…'}<button className="mt-4 block text-xs text-primary" onClick={()=>window.dispatchEvent(new Event('paperdesk:open-project'))}>打开项目…</button></div>:<div className="rounded-xl border border-border bg-card px-5">
 {category==='general'&&(global?<><TextAppearance kind="ui" /><Row label="界面强调色" hint="个人偏好，立即应用到选中项、按钮与高亮；当前界面使用深色主题。">{Object.entries(accents).map(([id,color])=><button key={id} aria-label={`${color.name}强调色`} aria-pressed={preferences.accent===id} title={color.name} onClick={()=>update({accent:id as keyof typeof accents})} className={`h-7 w-7 rounded-full border-2 ${preferences.accent===id?'border-foreground':'border-transparent'}`} style={{backgroundColor:`hsl(${color.hsl})`}} />)}</Row><h3 className="mt-6 text-sm font-medium">阅读器 · 文本预览</h3><TextAppearance kind="preview" /><p className="py-4 text-xs text-muted-foreground">三组字体偏好独立保存，源码外观在“编辑器”分类中设置。均不随论文项目共享。</p></>:<><Row label={project.name} hint="本地项目的目录权限与工具连接统一复用。"><button className={input} onClick={()=>window.dispatchEvent(new Event('paperdesk:connect-project'))}>项目连接</button></Row><Row label="位置已移动或不可访问？" hint="请打开迁移后的新位置，不需要重复配置每项工具。"><button className={input} onClick={()=>window.dispatchEvent(new Event('paperdesk:open-project'))}>打开项目…</button></Row></>)}
 {category==='editor'&&<>{global?<><Row label="编辑器字体" hint="字体不可用时自动回退到系统等宽字体。"><select aria-label="编辑器字体" className={input} value={preferences.fontFamily} onChange={e=>update({fontFamily:e.target.value as keyof typeof editorFonts})}>{Object.entries(editorFonts).map(([id,font])=><option key={id} value={id}>{font.name}</option>)}</select></Row><Row label="字号"><select aria-label="编辑器字号" className={input} value={preferences.fontSize} onChange={e=>update({fontSize:Number(e.target.value)})}>{[11,12.5,14,16,18].map(n=><option key={n} value={n}>{n} px</option>)}</select></Row><Row label="行高"><select aria-label="编辑器行高" className={input} value={preferences.lineHeight} onChange={e=>update({lineHeight:Number(e.target.value)})}>{[1.5,1.75,2].map(n=><option key={n}>{n}</option>)}</select></Row><Row label="Tab 显示宽度" hint="只改变制表符显示宽度，不重写现有文本。"><select aria-label="Tab 显示宽度" className={input} value={preferences.tabSize} onChange={e=>update({tabSize:Number(e.target.value)})}>{[2,4,8].map(n=><option key={n}>{n}</option>)}</select></Row></>:<p className="py-4 text-xs text-muted-foreground">字体、字号与行高继承个人偏好。<Link className="ml-2 text-primary" to="/settings/global/editor">修改全局编辑器外观</Link></p>}
 <Row label="实时 ChkTeX 检查" hint={global?'编辑停顿后检查当前未保存文本，不编译或保存文件。':`${inheritance('lintEnabled')} · 当前${effective.lintEnabled?'开启':'关闭'}`}><select disabled={busy} aria-label="实时检查设置" className={input} value={global?String(preferences.lintEnabled):configuration.overrides.lintEnabled===undefined?'inherit':String(configuration.overrides.lintEnabled)} onChange={e=>global?update({lintEnabled:e.target.value==='true'}):override('lintEnabled',e.target.value==='inherit'?undefined:e.target.value==='true')}>{!global&&<option value="inherit">继承全局</option>}<option value="true">开启</option><option value="false">关闭</option></select></Row>
 <Row label="禁用规则编号" hint={global?'只支持明确的规则编号；不执行配置字符串。':`${inheritance('disabledRules')} · 当前 ${effective.disabledRules.join(', ')||'不禁用规则'}`}><div>{!global&&configuration.overrides.disabledRules!==undefined&&<button className="mb-2 block text-xs text-primary" onClick={()=>override('disabledRules',undefined)}>恢复继承</button>}<Rules key={`${scope}:${effective.disabledRules.join(',')}`} disabled={busy} value={effective.disabledRules} onSave={rules=>global?update({disabledRules:rules}):override('disabledRules',rules)} /></div></Row></>}
 {category==='compile'&&<><Row label={global?'默认编译引擎':'编译引擎'} hint={global?'新项目默认继承；仅列出当前适配器支持的引擎。':`${inheritance('engine')} · 实际使用 ${effective.engine}`}><select disabled={busy} aria-label="设置编译引擎" className={input} value={global?preferences.engine:configuration.overrides.engine??'inherit'} onChange={e=>global?update({engine:e.target.value as Engine}):override('engine',e.target.value==='inherit'?undefined:e.target.value)}>{!global&&<option value="inherit">继承全局（{preferences.engine}）</option>}<option value="pdflatex">pdfLaTeX</option><option value="xelatex">XeLaTeX</option></select>{!global&&configuration.overrides.engine&&<button className="text-xs text-primary" onClick={()=>override('engine',undefined)}>恢复继承</button>}</Row>{!global&&<Row label="论文主 TeX 文件" hint="此项只属于当前项目，保存到 .paperdesk/project.json。"><select disabled={busy} aria-label="设置论文主文件" className={input+' max-w-xs'} value={project.rootId} onChange={e=>void save(configuration.overrides,e.target.value)}>{project.files.filter(f=>f.kind==='latex').map(file=><option key={file.id} value={file.id}>{file.path}</option>)}</select></Row>}<p className="py-4 text-xs text-muted-foreground">编译由工具栏手动触发，输出保存在 build；没有无效的自动编译或 LuaLaTeX 开关。</p></>}
 {category==='references'&&(global?<Row label="新项目默认启用 Git" hint="新建时仍可取消。本机缺少 Git 时会明确提示并关闭。"><input aria-label="新项目默认启用 Git" type="checkbox" checked={preferences.defaultGit} onChange={e=>update({defaultGit:e.target.checked})} /></Row>:<><Row label="版本管理" hint="查看当前项目的真实本地分支与文件状态，不自动提交。"><button className={input} onClick={()=>window.dispatchEvent(new Event('paperdesk:show-git'))}>查看 Git 状态</button></Row><Row label="项目 Bib 文件" hint="论文使用哪些文献库，由主 TeX 的 bibliography/addbibresource 声明决定。"><div className="text-right text-xs text-muted-foreground">{project.files.filter(file=>file.kind==='bib').map(file=><p key={file.id}>{file.path}</p>)}</div></Row><p className="py-4 text-xs text-muted-foreground">Zotero 同步尚未接入。AI 服务请在独立 AI 设置页配置。</p></>)}
 </div>}
 {global&&category==='general'&&<div className="mt-5 rounded-xl border border-border bg-card px-5"><Row label="快捷键" hint="在独立页面搜索、配置与重置命令快捷键。"><Link className="text-xs text-primary" to="/settings/global/shortcuts">打开快捷键设置</Link></Row></div>}
 {global&&category==='compile'&&<LocalTools />}
 </div></div></div></div>;
}
