import {useEffect,useState} from 'react';
import {useProject} from './context';import {dirtyFiles} from '@/lib/projectFiles';import {emptyProject} from '@/lib/initialProject';import {saveSession} from '@/lib/projectSession';
import {recentProjects,forgetRecentProject,matchingProjectRecords,forgetDeletedRecords,type RecentProject} from '@/lib/recentProjects';
import {matchingGitBindingKeys,forgetGitBindingKeys} from '@/lib/gitBinding';import {verifyDeletionTarget,deleteVerifiedProject,type DeletionTarget} from '@/lib/projectManagement';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
export function ProjectManagement(){
 const {project,setProject,closeProject,saveAll,busy,saving,setBusy,setMessage}=useProject();const [mode,setMode]=useState<'close'|'manage'|null>(null),[recent,setRecent]=useState<RecentProject[]>([]),[target,setTarget]=useState<FileSystemDirectoryHandle|null>(null),[plan,setPlan]=useState<DeletionTarget|null>(null),[typed,setTyped]=useState(''),[discard,setDiscard]=useState(false),[message,status]=useState('');
 useEffect(()=>{const close=()=>{setMode('close');setDiscard(false);status('');},manage=()=>{setMode('manage');status('');void recentProjects().then(setRecent).catch(error=>status(error.message));};window.addEventListener('paperdesk:close-project',close);window.addEventListener('paperdesk:manage-projects',manage);return()=>{window.removeEventListener('paperdesk:close-project',close);window.removeEventListener('paperdesk:manage-projects',manage);};},[]);
 const choose=(directory:FileSystemDirectoryHandle)=>{setTarget(directory);setPlan(null);setTyped('');setDiscard(false);status('');};
 const remove=async(entry:RecentProject)=>{try{await forgetRecentProject(entry.id);setRecent(items=>items.filter(item=>item.id!==entry.id));window.dispatchEvent(new Event('paperdesk:recent-updated'));status('已移除最近记录，磁盘文件与当前项目不变。');}catch(error){status(`移除失败：${(error as Error).message}`);}};
 const destroy=async()=>{if(!plan||busy||saving)return;setBusy(true);try{const isCurrent=!!project.directory&&(await project.directory.isSameEntry(plan.directory)||await plan.directory.resolve(project.directory)!==null);if(isCurrent&&dirtyFiles(project).length&&!discard)throw Error('当前项目有未保存修改，请先保存或勾选放弃。');const records=await matchingProjectRecords(plan.directory),bindingKeys=await matchingGitBindingKeys(plan.directory);await deleteVerifiedProject(plan,typed);
   const warnings:string[]=[];try{await forgetDeletedRecords(records);}catch{warnings.push('最近记录清理失败');}try{await forgetGitBindingKeys(bindingKeys);}catch{warnings.push('本机连接缓存清理失败');}
   if(isCurrent){const empty=emptyProject();try{await saveSession(empty);}catch{warnings.push('会话清理失败，刷新可能显示旧缓存');}if(import.meta.hot)import.meta.hot.data.project=empty;setProject(current=>current.id===project.id?empty:current);}
   setTarget(null);setPlan(null);try{setRecent(await recentProjects());}catch{warnings.push('最近列表刷新失败');}window.dispatchEvent(new Event('paperdesk:recent-updated'));setMessage(`目录已永久删除${warnings.length?'；'+warnings.join('；'):''}`);status(`目录已永久删除${warnings.length?'；'+warnings.join('；'):''}`);
  }catch(error){status((error as Error).message);}finally{setBusy(false);}};
 return <Dialog open={mode!==null} onOpenChange={open=>{if(!open&&!busy&&!saving){setMode(null);setTarget(null);setPlan(null);}}}><DialogContent className="max-h-[85vh] overflow-auto sm:max-w-xl"><DialogHeader><DialogTitle>{mode==='close'?'关闭当前项目':'管理项目'}</DialogTitle><DialogDescription>{mode==='close'?`${project.name} · 文件与最近记录保留。`:'移除记录不会删除文件；删除目录是独立的永久操作。'}</DialogDescription></DialogHeader>
 {mode==='close'?<><p className="text-sm">{dirtyFiles(project).length?`${dirtyFiles(project).length} 个文件有未保存修改。`:'关闭后返回空工作区。'}</p>{dirtyFiles(project).length>0&&<><button disabled={busy||saving} className="text-left text-sm text-primary" onClick={()=>void saveAll()}>先保存全部</button><label className="flex gap-2 text-sm"><input type="checkbox" checked={discard} onChange={e=>setDiscard(e.target.checked)} />放弃当前未保存修改</label></>}<button disabled={busy||saving||(!discard&&dirtyFiles(project).length>0)} onClick={()=>void closeProject(discard).then(()=>setMode(null)).catch(error=>status(error.message))} className="rounded bg-primary px-3 py-2 text-sm text-primary-foreground disabled:opacity-40">关闭项目</button></>:<><div className="flex items-center justify-between border-b border-border pb-3"><span className="text-sm">当前：{project.name}</span><button disabled={busy||saving||!project.directory} className="text-xs text-red-400 disabled:opacity-40" onClick={()=>project.directory&&choose(project.directory)}>删除当前目录…</button></div><div className="space-y-2">{recent.length?recent.map(entry=><div key={entry.id} className="flex items-center gap-3 rounded border border-border px-3 py-2"><span className="min-w-0 flex-1 truncate text-sm">{entry.name}</span><button disabled={busy||saving} className="text-xs text-primary" onClick={()=>void remove(entry)}>移除记录</button><button disabled={busy||saving} className="text-xs text-red-400" onClick={()=>entry.directory?choose(entry.directory):status("请先重新打开该项目目录以验证删除目标。")}>删除目录…</button></div>):<p className="text-sm text-muted-foreground">没有最近项目。</p>}</div>
 {target&&<div className="space-y-3 rounded border border-red-400/40 p-4"><h3 className="text-sm font-medium">永久删除：{target.name}</h3><p className="text-xs text-muted-foreground">将删除整个目录，包括论文、附件、build 和 Git 历史，不进入回收站。请先选择它的直接父目录以验证目标。</p><button disabled={busy||saving} className="text-sm text-primary" onClick={async()=>{try{if(!window.showDirectoryPicker)throw Error('浏览器不支持目录验证，请使用系统文件管理器。');const parent=await window.showDirectoryPicker({mode:'readwrite'});setPlan(await verifyDeletionTarget(parent,target));status('');}catch(error){setPlan(null);status((error as Error).name==='AbortError'?'已取消选择，未删除。':(error as Error).message);}}}>选择并验证父目录…</button>{plan&&<><p className="break-all text-sm">已验证目录：{plan.label}</p><p className="text-xs text-muted-foreground">浏览器不提供绝对路径；此目标已通过目录句柄身份验证。</p><input aria-label="确认删除项目目录名" value={typed} onChange={e=>setTyped(e.target.value)} placeholder={`输入 ${plan.name}`} className="w-full rounded border border-input bg-background p-2 text-sm" />{dirtyFiles(project).length>0&&<label className="flex gap-2 text-xs"><input type="checkbox" checked={discard} onChange={e=>setDiscard(e.target.checked)} />若删除的是当前项目，放弃其未保存修改</label>}<button disabled={busy||saving||typed!==plan.name} className="rounded bg-red-500 px-3 py-2 text-sm text-white disabled:opacity-40" onClick={()=>void destroy()}>确认永久删除目录</button></>}<button disabled={busy} className="ml-3 text-xs text-muted-foreground" onClick={()=>{setTarget(null);setPlan(null);}}>取消删除</button></div>}</>}
 {(busy||saving)&&<p className="text-xs text-muted-foreground">请等待当前操作完成。</p>}{message&&<p role="status" className="text-sm text-amber-300">{message}</p>}
 </DialogContent></Dialog>;
}
