import {useLayoutEffect,useMemo,useRef} from 'react';
import {parseDelimited,editDelimitedCell} from '@/lib/delimited';
import {usePreferences} from '@/settings/context';
import {textFonts,editorFonts} from '@/settings/model';
export function DelimitedEditor({source,delimiter,onChange,readOnly}:{source:string;delimiter:string;onChange:(source:string)=>void;readOnly:boolean}){
 const tableRef=useRef<HTMLTableElement>(null);
 const {preferences}=usePreferences();const parsed=useMemo(()=>{try{return {rows:parseDelimited(source,delimiter),error:''};}catch(error){return {rows:[],error:(error as Error).message};}},[source,delimiter]);
 useLayoutEffect(()=>{
  const table=tableRef.current;if(!table)return;
  const measure=()=>{const sample=table.querySelector('textarea');if(!sample)return;const computed=getComputedStyle(sample),span=document.createElement('span');Object.assign(span.style,{position:'fixed',visibility:'hidden',whiteSpace:'pre',font:computed.font,letterSpacing:computed.letterSpacing,tabSize:computed.tabSize});document.body.append(span);
   const widths:number[]=[];for(const row of parsed.rows)row.forEach((cell,column)=>{for(const line of cell.value.split(/\r\n|\r|\n/)){span.textContent=line; widths[column]=Math.max(widths[column]??48,Math.ceil(span.getBoundingClientRect().width)+32);}});span.remove();
   table.querySelectorAll('col').forEach((col,index)=>{col.style.width=`${index===0?48:widths[index-1]??48}px`;});table.style.width=`${48+widths.reduce((sum,width)=>sum+width,0)}px`;
  };measure();let active=true;void document.fonts.ready.then(()=>{if(active)measure();});return()=>{active=false;};
 },[parsed.rows,preferences.previewFontSize,preferences.previewFontFamily]);
 if(parsed.error)return <div className="flex h-full flex-col"><p role="alert" className="p-4 text-sm text-warning">{parsed.error} 表格编辑已暂停，请在下方修正源码。</p><textarea data-content-typography="editor" style={{fontFamily:editorFonts[preferences.fontFamily].css,fontSize:preferences.fontSize,lineHeight:preferences.lineHeight,tabSize:preferences.tabSize}} aria-label="表格源码修复" value={source} readOnly={readOnly} onChange={e=>onChange(e.target.value)} className="min-h-0 flex-1 bg-transparent p-4 font-editor" /></div>;
 if(!parsed.rows.length)return <textarea data-content-typography="editor" style={{fontFamily:editorFonts[preferences.fontFamily].css,fontSize:preferences.fontSize,lineHeight:preferences.lineHeight,tabSize:preferences.tabSize}} aria-label="空表格源码" value={source} readOnly={readOnly} onChange={e=>onChange(e.target.value)} className="h-full w-full bg-transparent p-4" placeholder="输入 CSV / TSV 首行" />;
 return <div data-content-typography="preview" className="h-full overflow-auto p-4" style={{fontFamily:textFonts[preferences.previewFontFamily].css,fontSize:preferences.previewFontSize}}><div className="data-table-frame"><table ref={tableRef} className="data-table table-fixed"><colgroup>{Array.from({length:1+parsed.rows.reduce((count,row)=>Math.max(count,row.length),0)},(_,i)=><col key={i} />)}</colgroup><tbody>{parsed.rows.map((row,r)=><tr key={r}><th scope="row" className="px-2 text-[.8em] font-normal">{r+1}</th>{row.map((cell,c)=>{const numeric=/^\s*-?[\d,]*\.?\d+\s*$/.test(cell.value)&&cell.value.trim()!=='';return <td key={c} className="align-top"><textarea aria-label={`第 ${r+1} 行第 ${c+1} 列`} readOnly={readOnly} rows={Math.min(8,Math.max(1,cell.value.split('\n').length))} value={cell.value} onChange={event=>onChange(editDelimitedCell(source,cell,event.target.value,delimiter))} className={`block min-h-9 w-full resize-y bg-transparent px-3 py-2 leading-relaxed outline-none focus:bg-accent/50 focus:ring-1 focus:ring-inset focus:ring-primary${numeric?' text-right':''}`} /></td>;})}</tr>)}</tbody></table></div></div>;
}
