import {useCallback,useEffect,useRef,useState,type ReactNode} from 'react';import {AgentContext} from './context';
import {agentStatus,agentRequest,agentChat,bindAgentDirectory,type AgentStatus,type AgentRecord,type AiConfig} from '@/lib/agentClient';import {useProject} from '@/project/context';import {gitPath} from '@/lib/gitBinding';import {readProject,dirtyFiles} from '@/lib/projectFiles';import {mergeDrafts} from '@/lib/projectSession';
interface ScopeState {record:AgentRecord|null;sessions:AgentRecord[];busy:boolean;error:string;ready:boolean;config:AiConfig|null}
const blank:ScopeState={record:null,sessions:[],busy:false,error:'',ready:false,config:null};
export function AgentProvider({children}:{children:ReactNode}){const {project,setProject,setBusy,busy:projectBusy}=useProject(),[status,setStatus]=useState<AgentStatus|null>(null),[scopes,setScopes]=useState<Record<string,ScopeState>>({});const scope=project.id,current=scopes[scope]??blank,controllers=useRef(new Map<string,AbortController>()),navigation=useRef(new Set<string>()),[navigating,setNavigating]=useState(false);
 const patch=useCallback((id:string,update:Partial<ScopeState>|((state:ScopeState)=>ScopeState))=>setScopes(all=>({...all,[id]:typeof update==='function'?update(all[id]??blank):{...(all[id]??blank),...update}})),[]);
 const refresh=useCallback(async()=>{const id=scope;try{const status=await agentStatus();setStatus(status);if(id==='empty'){patch(id,{...blank});return;}if(id!=='global'){if(!project.directory)throw Error('当前项目尚未连接本地目录；请在项目菜单完成连接。');const absolute=await gitPath(project.directory);if(!absolute)throw Error('请先在项目连接窗口填写目录路径，AI 不会使用其他工作区。');const result=await bindAgentDirectory(project.directory,absolute);if(result.project.id!==id){const fresh=await readProject(project.directory);setProject(current=>current.id===id?mergeDrafts(fresh,current):current);return;}}
 const result=await agentRequest<{sessions:AgentRecord[];settings:AiConfig;activeId?:string}>('sessions',{projectId:id});const selected=result.activeId??result.sessions[0]?.id;const record=selected?await agentRequest<AgentRecord>('session',{projectId:id,sessionId:selected}):null;patch(id,state=>({...state,ready:true,error:'',config:result.settings,sessions:state.busy?state.sessions:result.sessions,record:state.busy?state.record:record}));}catch(error){patch(id,{ready:false,error:/ENOENT|NotFound|不存在|已移动/.test((error as Error).message)?'项目目录已移动或无法访问，请在项目菜单重新连接正确位置。':(error as Error).message});}},[scope,project.directory,setProject,patch]);
 useEffect(()=>()=>{controllers.current.get(scope)?.abort();},[scope]);
 useEffect(()=>{void refresh();},[refresh]);useEffect(()=>{const listener=()=>{void refresh();};window.addEventListener('envoi:ai-configured',listener);window.addEventListener('envoi:connection-updated',listener);return()=>{window.removeEventListener('envoi:ai-configured',listener);window.removeEventListener('envoi:connection-updated',listener);};},[refresh]);
 const select=async(sessionId:string)=>{if(current.busy||controllers.current.has(scope)||navigation.current.has(scope))return;navigation.current.add(scope);setNavigating(true);try{patch(scope,{record:await agentRequest<AgentRecord>('session',{projectId:scope,sessionId}),error:''});}catch(error){patch(scope,{error:(error as Error).message});}finally{navigation.current.delete(scope);setNavigating(false);}};
 const newSession=async()=>{if(current.busy||controllers.current.has(scope)||navigation.current.has(scope))return;navigation.current.add(scope);setNavigating(true);try{const record=await agentRequest<AgentRecord>('new',{projectId:scope});patch(scope,state=>({...state,record,sessions:[record,...state.sessions],error:''}));}catch(error){patch(scope,{error:(error as Error).message});}finally{navigation.current.delete(scope);setNavigating(false);}};
 const send=async(message:string,context?:string)=>{const id=scope;if(!current.ready||current.busy||controllers.current.has(id)||navigation.current.has(id))return;const controller=new AbortController();let sessionId=current.record?.id;const writes=current.config?.tools==='write';if(writes&&projectBusy){patch(id,{error:'请等待当前项目操作结束。'});return;}if(writes&&dirtyFiles(project).length){patch(id,{error:'请先保存全部草稿，再启用文件修改任务。'});return;}controllers.current.set(id,controller);if(writes)setBusy(true);
 patch(id,state=>({...state,busy:true,error:'',record:{...(state.record??{id:'pending',name:'新会话',status:'running'}),messages:[...(state.record?.messages??[]),{id:crypto.randomUUID(),role:'user',text:message},{id:crypto.randomUUID(),role:'assistant',text:''}]}}));
 try{for await(const event of agentChat(message,{projectId:id,sessionId,context,dirty:dirtyFiles(project).length>0,signal:controller.signal})){if(event.type==='session'){sessionId=event.id;patch(id,state=>({...state,record:state.record?{...state.record,id:event.id}:null}));}if(event.type==='delta')patch(id,state=>({...state,record:state.record?{...state.record,messages:state.record.messages.map((item,index)=>index===state.record!.messages.length-1?{...item,text:item.text+event.text}:item)}:null}));if(event.type==='error')throw Error(event.message);}
 }catch(error){patch(id,{error:controller.signal.aborted?'任务已停止。':(error as Error).message});}finally{navigation.current.add(id);controllers.current.delete(id);if(writes)setBusy(false);if(sessionId){try{const record=await agentRequest<AgentRecord>('session',{projectId:id,sessionId});patch(id,state=>({...state,record,sessions:[record,...state.sessions.filter(item=>item.id!==record.id)]}));}catch{/* Stream error already shown. */}}if(writes&&project.directory){try{const fresh=await readProject(project.directory);setProject(current=>current.id===project.id?mergeDrafts(fresh,current):current);}catch(error){patch(id,{error:'请重新打开项目以刷新工具修改：'+(error as Error).message});}}navigation.current.delete(id);patch(id,{busy:false});}
 };
 const stop=()=>{controllers.current.get(scope)?.abort();if(current.record?.id)void agentRequest('abort',{projectId:scope,sessionId:current.record.id}).catch(()=>{});};
 const remove=async(id:string)=>{try{await agentRequest('history/delete',{projectId:scope,sessionId:id,confirm:true});patch(scope,state=>({...state,record:state.record?.id===id?null:state.record,sessions:state.sessions.filter(item=>item.id!==id)}));}catch(error){patch(scope,{error:(error as Error).message});}};
 return <AgentContext.Provider value={{status,scope,record:current.record,sessions:current.sessions,busy:current.busy,navigating,error:current.error,ready:current.ready,config:current.config,refresh,select,newSession,send,stop,remove}}>{children}</AgentContext.Provider>;
}
