import {translate} from '@/i18n/runtime';
export interface AiConfig {provider?:string|null;thinking?:string|null;model:string|null;context:'none'|'current';tools:'none'|'read'|'write'}
export interface ModelCatalog {state:string;source:string;visibility?:string;checkedAt?:number;error?:string;message?:string;unresolved?:number}
export interface AgentStatus {available:boolean;runtime:boolean;error?:string;token:string;providers:{id:string;name:string;oauth:boolean;apiKey?:boolean;catalog?:ModelCatalog;auth:{configured:boolean;source?:string}}[];models:{id:string;provider:string;name:string;thinkingLevels:string[];available:boolean;unavailableReason?:string}[];settings:AiConfig;storage:{dataDir:string;credentials:string;kind:string}}
export interface AgentMessage{id:string;role:'user'|'assistant';text:string;tools?:{name:string;phase:string;isError?:boolean}[];error?:string}
export interface AgentRecord{created?:number;id:string;name:string;messages:AgentMessage[];status:string;running?:boolean;count?:number}
export async function agentStatus(signal?:AbortSignal):Promise<AgentStatus>{const response=await fetch('/api/envoi/agent',{signal});if(!response.ok||!response.headers.get('content-type')?.includes('application/json'))throw Error(translate('ai.serviceNotConnected'));return response.json();}
export async function agentRequest<T=unknown>(route:string,body:unknown,signal?:AbortSignal):Promise<T>{const status=await agentStatus(signal);const response=await fetch('/api/envoi/agent/'+route,{method:'POST',signal,headers:{'Content-Type':'application/json','X-Envoi-Token':status.token},body:JSON.stringify(body)});const result=await response.json();if(!response.ok)throw Error(result.error??translate('ai.operationFailed'));return result;}
const bindings=new WeakMap<FileSystemDirectoryHandle,{path:string;token:string;promise:Promise<{ok:boolean;project:{id:string;path:string;name:string}}>}>();
export async function bindAgentDirectory(directory:FileSystemDirectoryHandle,absolutePath:string,copy=false){const status=await agentStatus();const previous=bindings.get(directory);if(!copy&&previous?.path===absolutePath&&previous.token===status.token)return previous.promise;
 const promise=(async()=>{const proof=Array.from(crypto.getRandomValues(new Uint8Array(32)),byte=>byte.toString(16).padStart(2,'0')).join(''),name='agent-proof-'+proof;const folder=await directory.getDirectoryHandle('.envoi',{create:true}),handle=await folder.getFileHandle(name,{create:true}),stream=await handle.createWritable();await stream.write(proof);await stream.close();try{return await agentRequest<{ok:boolean;project:{id:string;path:string;name:string}}>('bind',{directory:absolutePath,proof,proofKind:'agent',copy});}finally{await folder.removeEntry(name).catch(()=>{});}})();
 bindings.set(directory,{path:absolutePath,token:status.token,promise});try{return await promise;}catch(error){bindings.delete(directory);throw error;}
}
export type ChatEvent={type:'delta'|'thinking';text:string}|{type:'session';id:string}|{type:'tool';phase:string;name:string;isError?:boolean}|{type:'done'}|{type:'error';message:string};
export async function* agentChat(message:string,options:{projectId:string;sessionId?:string;context?:string;dirty:boolean;signal?:AbortSignal}):AsyncGenerator<ChatEvent>{const status=await agentStatus(options.signal),response=await fetch('/api/envoi/agent/chat',{method:'POST',signal:options.signal,headers:{'Content-Type':'application/json','X-Envoi-Token':status.token},body:JSON.stringify({message,...options,signal:undefined})});if(!response.ok||!response.body){const error=await response.json();throw Error(error.error??translate('ai.requestFailed'));}const reader=response.body.getReader(),decoder=new TextDecoder();let buffer='';try{for(;;){const chunk=await reader.read();if(chunk.done){buffer+=decoder.decode();if(buffer.trim())yield JSON.parse(buffer);break;}buffer+=decoder.decode(chunk.value,{stream:true});let index;while((index=buffer.indexOf('\n'))>=0){const line=buffer.slice(0,index).trim();buffer=buffer.slice(index+1);if(line)yield JSON.parse(line);}}}finally{reader.releaseLock();}}
