import {translate} from '@/i18n/runtime';
export interface NativeValue<T>{revision:number;value:T;migration?:{archived:boolean;new:boolean}}
let runtime:Promise<{token:string;dataDir:string}>|undefined;
async function status(){return runtime??=fetch('/api/envoi/data').then(async response=>{if(!response.ok||!response.headers.get('content-type')?.includes('application/json'))throw Error(translate('storage.notConnected'));return response.json();}).catch(error=>{runtime=undefined;throw error;});}
async function request<T>(body:unknown,retry=true):Promise<T>{const info=await status(),response=await fetch('/api/envoi/data/store',{method:'POST',headers:{'Content-Type':'application/json','X-Envoi-Token':info.token},body:JSON.stringify(body)});if((response.status===403||response.status===401)&&retry){runtime=undefined;return request<T>(body,false);}const result=await response.json();if(!response.ok)throw Error(result.error??translate('storage.saveFailed'));return result;}
export const nativeGet=<T>(store:string,key='default')=>request<NativeValue<T>|null>({store,key,action:'get'});
export const nativePut=<T>(store:string,value:T,key='default',options:{migrate?:boolean;expectedRevision?:number}={})=>request<NativeValue<T>>({store,key,action:'put',value,...options});
export async function encodeNative(value:unknown):Promise<unknown>{if(value instanceof Blob){const bytes=new Uint8Array(await value.arrayBuffer());let binary='';for(let i=0;i<bytes.length;i+=32768)binary+=String.fromCharCode(...bytes.subarray(i,i+32768));return {$blob:btoa(binary),type:value.type,name:value instanceof File?value.name:undefined,lastModified:value instanceof File?value.lastModified:undefined};}if(Array.isArray(value))return Promise.all(value.map(encodeNative));if(value&&typeof value==='object'){const result:Record<string,unknown>={};for(const [key,entry] of Object.entries(value)){if(['directory','handle'].includes(key)||key==='url'&&typeof entry==='string'&&entry.startsWith('blob:'))continue;result[key]=await encodeNative(entry);}return result;}return value;}
export function decodeNative(value:unknown):unknown{if(Array.isArray(value))return value.map(decodeNative);if(value&&typeof value==='object'){const raw=value as Record<string,unknown>;if(typeof raw.$blob==='string'){const bytes=Uint8Array.from(atob(raw.$blob),c=>c.charCodeAt(0));return raw.name?new File([bytes],String(raw.name),{type:String(raw.type??''),lastModified:Number(raw.lastModified)||0}):new Blob([bytes],{type:String(raw.type??'')});}return Object.fromEntries(Object.entries(raw).map(([key,entry])=>[key,decodeNative(entry)]));}return value;}
export async function nativeMigrate<T>(store:string,legacy:T,key='default'){const old=await nativeGet<T>(store,key);if(old){if(JSON.stringify(old.value)!==JSON.stringify(legacy)){const result=await nativePut(store,legacy,key,{migrate:true});if(result.migration?.new&&typeof window!=='undefined')window.dispatchEvent(new CustomEvent('envoi:storage-warning',{detail:translate('storage.legacyArchived')}));}return old;}return nativePut(store,legacy,key,{expectedRevision:0});}
